from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from google import genai
from google.genai import types
from PIL import Image, ImageEnhance, ImageFilter, ImageDraw, ImageFont
import cv2
import numpy as np
import io
import os
import uuid
from pathlib import Path
from dotenv import load_dotenv
import base64

load_dotenv()

app = FastAPI()

# CORS middleware for React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request logging middleware
@app.middleware("http")
async def log_requests(request, call_next):
    print(f"\n=== Incoming Request ===")
    print(f"Method: {request.method}")
    print(f"URL: {request.url}")
    print(f"Headers: {dict(request.headers)}")
    
    # For debugging form data
    if request.method == "POST":
        # We need to read the body, but this consumes it
        # So we'll just log what we can without consuming
        print(f"Content-Type: {request.headers.get('content-type')}")
    
    response = await call_next(request)
    print(f"Response status: {response.status_code}")
    print(f"======================\n")
    return response

# Initialize Gemini client
client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

# Use temp directory for temporary files
import tempfile
TEMP_DIR = Path(tempfile.gettempdir()) / "ai_image_editor"
TEMP_DIR.mkdir(exist_ok=True)

@app.get("/")
def read_root():
    return {"message": "AI Image Editor API"}

@app.post("/api/upload")
async def upload_image(file: UploadFile = File(...)):
    """Upload and save image temporarily"""
    try:
        file_id = str(uuid.uuid4())
        file_ext = file.filename.split(".")[-1]
        filename = f"{file_id}.{file_ext}"
        filepath = TEMP_DIR / filename
        
        contents = await file.read()
        with open(filepath, "wb") as f:
            f.write(contents)
        
        return {"filename": filename, "file_id": file_id}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/ai-edit")
async def ai_edit(
    file: UploadFile = File(...),
    prompt: str = Form(...)
):
    """AI-powered natural language editing"""
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        # Use exact format from official snippet
        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[prompt, image],
        )
        
        for part in response.parts:
            if part.text is not None:
                print(part.text)
            elif part.inline_data is not None:
                output_id = str(uuid.uuid4())
                output_path = TEMP_DIR / f"{output_id}.png"
                image = part.as_image()
                image.save(str(output_path))
                
                return FileResponse(
                    output_path,
                    media_type="image/png",
                    headers={"X-Filename": f"{output_id}.png"}
                )
        
        raise HTTPException(status_code=500, detail="No image generated by model")
    except Exception as e:
        print(f"AI Edit Error: {type(e).__name__}: {e}")
        raise HTTPException(status_code=500, detail=f"AI editing failed: {str(e)}")

@app.post("/api/remove-background")
async def remove_background(file: UploadFile = File(...)):
    """AI-powered background removal"""
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        prompt = "Remove the background from this image completely, making it transparent. Keep only the main subject in focus."
        
        # Use exact format from official snippet
        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[prompt, image],
        )
        
        for part in response.parts:
            if part.text is not None:
                print(part.text)
            elif part.inline_data is not None:
                output_id = str(uuid.uuid4())
                output_path = TEMP_DIR / f"{output_id}.png"
                image = part.as_image()
                image.save(str(output_path))
                
                return FileResponse(
                    output_path,
                    media_type="image/png",
                    headers={"X-Filename": f"{output_id}.png"}
                )
        
        raise HTTPException(status_code=500, detail="No image generated by model")
    except Exception as e:
        print(f"Remove BG Error: {type(e).__name__}: {e}")
        raise HTTPException(status_code=500, detail=f"Background removal failed: {str(e)}")

@app.post("/api/generative-fill")
async def generative_fill(
    file: UploadFile = File(...),
    prompt: str = Form(...)
):
    """Generative fill and inpainting"""
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        fill_prompt = f"Perform inpainting on this image: {prompt}. Fill in or modify the specified areas naturally and seamlessly."
        
        # Use exact format from official snippet
        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[fill_prompt, image],
        )
        
        for part in response.parts:
            if part.text is not None:
                print(part.text)
            elif part.inline_data is not None:
                output_id = str(uuid.uuid4())
                output_path = TEMP_DIR / f"{output_id}.png"
                image = part.as_image()
                image.save(str(output_path))
                
                return FileResponse(
                    output_path,
                    media_type="image/png",
                    headers={"X-Filename": f"{output_id}.png"}
                )
        
        raise HTTPException(status_code=500, detail="No image generated by model")
    except Exception as e:
        print(f"Gen Fill Error: {type(e).__name__}: {e}")
        raise HTTPException(status_code=500, detail=f"Generative fill failed: {str(e)}")

@app.post("/api/crop")
async def crop_image(
    file: UploadFile = File(...),
    x: int = Form(0),
    y: int = Form(0),
    width: int = Form(100),
    height: int = Form(100)
):
    """Crop image to specified dimensions
    
    Coordinates are in image space (actual pixel coordinates).
    PIL's crop() method uses box=(left, upper, right, lower) format.
    Reference: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop
    """
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        # Get image dimensions
        img_width, img_height = image.size
        
        print(f"Crop request: x={x}, y={y}, width={width}, height={height}")
        print(f"Image dimensions: {img_width}x{img_height}")
        
        # Clamp coordinates to image bounds
        x = max(0, min(x, img_width - 1))
        y = max(0, min(y, img_height - 1))
        
        # Calculate bottom-right corner
        x2 = min(x + width, img_width)
        y2 = min(y + height, img_height)
        
        # Ensure we have a valid crop area (at least 1x1 pixel)
        if x2 <= x or y2 <= y:
            raise ValueError(f"Invalid crop area: box=({x}, {y}, {x2}, {y2})")
        
        print(f"Cropping with box: ({x}, {y}, {x2}, {y2})")
        print(f"Crop dimensions: {x2-x}x{y2-y}")
        
        # PIL crop uses (left, upper, right, lower) format
        cropped = image.crop((x, y, x2, y2))
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        cropped.save(output_path, "PNG")
        
        print(f"Crop successful: saved to {output_path}")
        
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        print(f"Crop error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/add-text")
async def add_text(
    file: UploadFile = File(...),
    text: str = Form(...),
    x: int = Form(50),
    y: int = Form(50),
    size: int = Form(40),
    color: str = Form("#FFFFFF")
):
    """Add text to image"""
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        draw = ImageDraw.Draw(image)
        try:
            font = ImageFont.truetype("arial.ttf", size)
        except:
            font = ImageFont.load_default()
        
        # Convert hex color to RGB
        color_rgb = tuple(int(color.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
        draw.text((x, y), text, fill=color_rgb, font=font)
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        image.save(output_path, "PNG")
        
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/adjust")
async def adjust_image(
    file: UploadFile = File(...),
    brightness: float = Form(1.0),
    contrast: float = Form(1.0),
    saturation: float = Form(1.0),
    sharpness: float = Form(1.0)
):
    """Adjust brightness, contrast, saturation, and sharpness"""
    try:
        print(f"Adjust params: brightness={brightness}, contrast={contrast}, saturation={saturation}, sharpness={sharpness}")
        
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        if brightness != 1.0:
            enhancer = ImageEnhance.Brightness(image)
            image = enhancer.enhance(brightness)
        
        if contrast != 1.0:
            enhancer = ImageEnhance.Contrast(image)
            image = enhancer.enhance(contrast)
        
        if saturation != 1.0:
            enhancer = ImageEnhance.Color(image)
            image = enhancer.enhance(saturation)
        
        if sharpness != 1.0:
            enhancer = ImageEnhance.Sharpness(image)
            image = enhancer.enhance(sharpness)
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        image.save(output_path, "PNG")
        
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        print(f"Adjust error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/filter")
async def apply_filter(
    file: UploadFile = File(...),
    filter_type: str = Form(...)
):
    """Apply filters using OpenCV"""
    try:
        print(f"Filter request: filter_type={filter_type}, file={file.filename}")
        image_data = await file.read()
        print(f"Image data size: {len(image_data)} bytes")
        nparr = np.frombuffer(image_data, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        
        if img is None:
            raise ValueError("Failed to decode image")
        
        if filter_type == "blur":
            img = cv2.GaussianBlur(img, (15, 15), 0)
        elif filter_type == "sharpen":
            kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
            img = cv2.filter2D(img, -1, kernel)
        elif filter_type == "edge":
            img = cv2.Canny(img, 100, 200)
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        elif filter_type == "emboss":
            kernel = np.array([[-2,-1,0], [-1,1,1], [0,1,2]])
            img = cv2.filter2D(img, -1, kernel)
        elif filter_type == "sepia":
            kernel = np.array([[0.272, 0.534, 0.131],
                             [0.349, 0.686, 0.168],
                             [0.393, 0.769, 0.189]])
            img = cv2.transform(img, kernel)
        elif filter_type == "vintage":
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = np.array(img, dtype=np.float64)
            img[:,:,0] = img[:,:,0] * 0.9
            img[:,:,2] = img[:,:,2] * 1.1
            img = np.clip(img, 0, 255).astype(np.uint8)
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        elif filter_type == "grayscale":
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        else:
            raise ValueError(f"Invalid filter type: {filter_type}")
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        success = cv2.imwrite(str(output_path), img)
        
        if not success:
            raise ValueError("Failed to write image")
        
        print(f"Filter successful: saved to {output_path}")
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        print(f"Filter error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/rotate")
async def rotate_image(
    file: UploadFile = File(...),
    angle: int = Form(...)
):
    """Rotate image by specified angle"""
    try:
        print(f"=== Rotate Request ===")
        print(f"Angle: {angle} (type: {type(angle)})")
        print(f"File: {file.filename}, content_type: {file.content_type}")
        image_data = await file.read()
        print(f"Image data size: {len(image_data)} bytes")
        image = Image.open(io.BytesIO(image_data))
        
        rotated = image.rotate(-angle, expand=True)
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        rotated.save(output_path, "PNG")
        
        print(f"Rotation successful: saved to {output_path}")
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        print(f"Rotate error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/flip")
async def flip_image(
    file: UploadFile = File(...),
    direction: str = Form(...)
):
    """Flip image horizontally or vertically"""
    try:
        print(f"Flip request: direction={direction}, file={file.filename}")
        image_data = await file.read()
        print(f"Image data size: {len(image_data)} bytes")
        image = Image.open(io.BytesIO(image_data))
        
        if direction == "horizontal":
            flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
        elif direction == "vertical":
            flipped = image.transpose(Image.FLIP_TOP_BOTTOM)
        else:
            raise ValueError(f"Invalid direction: {direction}")
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.png"
        flipped.save(output_path, "PNG")
        
        print(f"Flip successful: saved to {output_path}")
        return FileResponse(output_path, media_type="image/png")
    except Exception as e:
        print(f"Flip error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/compress")
async def compress_image(
    file: UploadFile = File(...),
    quality: int = Form(85)
):
    """Compress image with specified quality (1-100)"""
    try:
        print(f"Compress request: quality={quality}")
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        # Clamp quality between 1 and 100
        quality = max(1, min(100, quality))
        
        output_id = str(uuid.uuid4())
        output_path = TEMP_DIR / f"{output_id}.jpg"
        
        # Convert RGBA to RGB for JPEG compression
        if image.mode in ('RGBA', 'LA', 'P'):
            background = Image.new('RGB', image.size, (255, 255, 255))
            if image.mode == 'P':
                image = image.convert('RGBA')
            background.paste(image, mask=image.split()[-1] if image.mode == 'RGBA' else None)
            image = background
        
        # Save with specified quality
        image.save(output_path, "JPEG", quality=quality, optimize=True)
        
        # Get file size
        file_size = output_path.stat().st_size
        file_size_kb = file_size / 1024
        
        print(f"Compressed to {file_size_kb:.2f} KB at quality {quality}")
        
        return FileResponse(
            output_path, 
            media_type="image/jpeg",
            headers={
                "X-File-Size": str(file_size),
                "X-File-Size-KB": f"{file_size_kb:.2f}"
            }
        )
    except Exception as e:
        print(f"Compress error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/convert")
async def convert_format(
    file: UploadFile = File(...),
    format: str = Form("png")
):
    """Convert image format"""
    try:
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data))
        
        output_id = str(uuid.uuid4())
        
        if format == "png":
            output_path = TEMP_DIR / f"{output_id}.png"
            image.save(output_path, "PNG", optimize=True)
            media_type = "image/png"
        elif format in ["jpg", "jpeg"]:
            if image.mode in ('RGBA', 'LA', 'P'):
                # Convert to RGB for JPEG (no transparency support)
                background = Image.new('RGB', image.size, (255, 255, 255))
                if image.mode == 'P':
                    image = image.convert('RGBA')
                background.paste(image, mask=image.split()[-1] if image.mode == 'RGBA' else None)
                image = background
            output_path = TEMP_DIR / f"{output_id}.jpg"
            image.save(output_path, "JPEG", quality=95, optimize=True)
            media_type = "image/jpeg"
        elif format == "webp":
            output_path = TEMP_DIR / f"{output_id}.webp"
            image.save(output_path, "WEBP", quality=90)
            media_type = "image/webp"
        elif format == "bmp":
            if image.mode == 'RGBA':
                image = image.convert('RGB')
            output_path = TEMP_DIR / f"{output_id}.bmp"
            image.save(output_path, "BMP")
            media_type = "image/bmp"
        elif format == "tiff":
            output_path = TEMP_DIR / f"{output_id}.tiff"
            image.save(output_path, "TIFF", compression="tiff_deflate")
            media_type = "image/tiff"
        elif format == "gif":
            if image.mode == 'RGBA':
                image = image.convert('RGB')
            output_path = TEMP_DIR / f"{output_id}.gif"
            image.save(output_path, "GIF", optimize=True)
            media_type = "image/gif"
        elif format == "ico":
            if image.mode == 'RGBA':
                image = image.convert('RGB')
            output_path = TEMP_DIR / f"{output_id}.ico"
            # ICO format typically uses smaller sizes
            image.thumbnail((256, 256), Image.Resampling.LANCZOS)
            image.save(output_path, "ICO")
            media_type = "image/x-icon"
        else:
            raise HTTPException(status_code=400, detail=f"Unsupported format: {format}")
        
        print(f"Converted to {format.upper()}: saved to {output_path}")
        return FileResponse(output_path, media_type=media_type)
    except Exception as e:
        print(f"Convert error: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
